"""Asynchronous card description enricher using local Ollama LLM for Agilent Native Suite."""

import asyncio
import logging
import re
from pathlib import Path
from typing import Dict, Any
import httpx
from agilent_native.config import config
from agilent_native.db import db

logger = logging.getLogger(__name__)
HISTORY_LOG_FILE = Path(".atl/ollama-history.log")


def _append_to_history(change_name: str, phase: str, prompt: str, response: str) -> None:
    """Record prompt and LLM response to local audit log."""
    try:
        HISTORY_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        entry = (
            f"=== [{change_name} | Phase: {phase}] ===\n"
            f"--- PROMPT SENT TO OLLAMA ({config.ollama_model}) ---\n"
            f"{prompt}\n"
            f"--- RESPONSE GENERATED BY OLLAMA ---\n"
            f"{response}\n"
            f"==================================================\n\n"
        )
        with open(HISTORY_LOG_FILE, "a", encoding="utf-8") as f:
            f.write(entry)
    except Exception as e:
        logger.warning(f"Failed to append to Ollama audit log: {e}")


def markdown_to_native_plane_html(md: str, change_name: str, phase: str, payload: Dict[str, Any] = None) -> str:
    """Convert Ollama markdown into clean, native HTML with timeline, testing, and release badges."""
    data = payload or {}
    clean_md = re.sub(r"```(?:markdown)?", "", md).replace("```", "").strip()

    html_parts = []
    html_parts.append(f"<p><strong>SDD Initiative / Task</strong>: <code>{change_name}</code> | <strong>Phase</strong>: <code>{phase.upper()}</code></p>")

    # Metadata badges: Timeline Dates, Tests, Release
    dates_info = []
    if "start_date" in data:
        dates_info.append(f"<strong>Start Date</strong>: {data['start_date']}")
    if "target_date" in data or "completed_date" in data:
        dates_info.append(f"<strong>Completed Date</strong>: {data.get('target_date') or data.get('completed_date')}")
    if "release_date" in data or "release" in data:
        dates_info.append(f"<strong>Release Tag</strong>: <code>{data.get('release_date') or data.get('release')}</code>")

    if dates_info:
        html_parts.append(f"<p>📅 {' | '.join(dates_info)}</p>")

    if "test_results" in data or "tests" in data:
        test_detail = data.get("test_results") or data.get("tests")
        html_parts.append(f"<p>🧪 <strong>Test Suite Status</strong>: <code>{test_detail}</code></p>")

    html_parts.append("<hr />")

    for line in clean_md.split("\n"):
        line = line.strip()
        if not line:
            continue

        if line.startswith("### "):
            html_parts.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html_parts.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html_parts.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("- [x]") or line.startswith("* [x]"):
            html_parts.append(f"<p>☑ <s>{line[5:].strip()}</s></p>")
        elif line.startswith("- [ ]") or line.startswith("* [ ]"):
            html_parts.append(f"<p>☐ {line[5:].strip()}</p>")
        elif line.startswith("- **") or line.startswith("* **"):
            parts = line[2:].split("**", 2)
            if len(parts) >= 3:
                key, val = parts[1], parts[2]
                html_parts.append(f"<p>• <strong>{key}</strong>{val}</p>")
            else:
                html_parts.append(f"<p>• {line[2:]}</p>")
        elif line.startswith("- ") or line.startswith("* "):
            html_parts.append(f"<p>• {line[2:]}</p>")
        else:
            html_parts.append(f"<p>{line}</p>")

    return "".join(html_parts)


async def generate_ollama_narrative(change_name: str, phase: str, payload: Dict[str, Any]) -> str:
    """Generate a rich SDLC narrative description using local Ollama."""
    prompt = f"""You are an agile technical documentation assistant for the initiative/task '{change_name}'.
Phase/Status completed: {phase}
Payload metadata & timeline: {payload}

Generate a clean markdown card body summary (max 150 words) including:
- High-level SDLC status & timeline (start/completion dates if present)
- Key deliverables completed & architecture scope
- Verification test suite results & release notes (if present)
- Open stoppers or risks (if any)
Keep it clean, professional, and structured."""

    url = f"{config.ollama_base_url.rstrip('/')}/api/generate"
    req_body = {
        "model": config.ollama_model,
        "prompt": prompt,
        "stream": False,
    }

    markdown_response = ""
    async with httpx.AsyncClient(timeout=30.0) as client:
        try:
            resp = await client.post(url, json=req_body)
            if resp.status_code == 200:
                data = resp.json()
                markdown_response = data.get("response", "").strip()
            else:
                logger.warning(f"Ollama returned status {resp.status_code}")
        except Exception as e:
            logger.warning(f"Failed to connect to Ollama at {url}: {e}")

    if not markdown_response:
        markdown_response = f"""### Task Phase Update: {phase.upper()}
- **Initiative**: `{change_name}`
- **Phase Status**: Completed
- **Artifact Ref**: `{payload.get('artifact_ref', 'N/A')}`
"""

    _append_to_history(change_name, phase, prompt, markdown_response)
    return markdown_to_native_plane_html(markdown_response, change_name, phase, payload=payload)


def enrich_card_async(work_item_id: str, change_name: str, phase: str, payload: Dict[str, Any]) -> None:
    """Trigger background task for Ollama card description enrichment."""

    async def _runner():
        try:
            description_html = await generate_ollama_narrative(change_name, phase, payload)
            db.update_work_item(work_item_id, {"description_html": description_html})
            logger.info(f"Asynchronously enriched Work Item '{work_item_id}' via Ollama.")
        except Exception as e:
            logger.warning(f"Error during async Ollama enrichment: {e}")

    try:
        loop = asyncio.get_running_loop()
        loop.create_task(_runner())
    except RuntimeError:
        asyncio.run(_runner())
